
export let dataMovie = [
    {id:1,
    title:"Star Wars Episodio I: La Amenaza Fantasma",
    image:"https://res.cloudinary.com/duvugx7r9/image/upload/v1717109985/proyectCinema/el-hipnotico-afiche-de-la-pelicula-sobre-la-pared-364KBLNBIJCSVFKQ7322KOSSCE_zywodu.avif",
    director:"George Lucas",
    year:1999,
    trailer:"https://www.youtube.com/watch?v=bD7bpG-zDJQ",
    sinopsis:"Obi-Wan Kenobi es un joven aprendiz caballero Jedi bajo la tutela de Qui-Gon Jinn; Anakin Skywalker, quien después será padre de Luke Skywalker y se convertirá en Darth Vader, solamente es un niño de 9 años. Cuando la Federación de Comercio corta todas las rutas al planeta Naboo, Qui-Gon y Obi-Wan son asignados para solucionar el problema."},

    {id:2,
    title:"Star Wars Episodio II: La Guerra de los Clones",
    image:"https://res.cloudinary.com/duvugx7r9/image/upload/v1717110078/proyectCinema/image-1652536806_qvdnrl.jpg",
    director:"George Lucas",
    year:2002,
    trailer:"https://www.youtube.com/watch?v=gYbW1F_c9eM",
    sinopsis:"En el Senado Galáctico reina la inquietud. Varios miles de sistemas solares han declarado su intención de abandonar la República. Este movimiento separatista, liderado por el misterioso conde Dooku, ha provocado que al limitado número de caballeros Jedi les resulte difícil mantener la paz y el orden en la galaxia. La senadora Amidala, antigua Reina de Naboo, regresa al Senado Galáctico para dar su voto en la crítica cuestión de crear un ejército de la República que ayude a los desbordados Jedi."},

    {id:3,
    title:"Star Wars Episodio 3: La venganza de los Sith",
    image:"https://res.cloudinary.com/duvugx7r9/image/upload/v1717110052/proyectCinema/peliculas-mas-taquilleras-verano-1975_30_sfxrb3.webp",
    director:"George Lucas",
    year:2005,
    trailer:"https://www.youtube.com/watch?v=5UnjrG_N8hU",
    sinopsis:"¡Guerra! La República se desmorona bajo los ataques del despiadado Lord Sith, el conde Dooku. Hay héroes en ambos bandos, pero el mal está por doquier. En una contundente jugada, el diabólico líder droide, el general Grievous, ha irrumpido en la capital de la República y ha secuestrado al Canciller Palpatine, líder del senado Galáctico. Mientras el ejército droide separatista trata de huir con su valioso rehén, dos caballeros Jedi inician una misión desesperada para liberar al Canciller cautivo."},

    {id:4,
    title:"Star Wars Episodio IV: Una Nueva Esperanza",
    image:"https://res.cloudinary.com/duvugx7r9/image/upload/v1717109937/proyectCinema/IV-6_bcul8d.jpg",
    director:"George Lucas",
    year:1977,
    trailer:"https://www.youtube.com/watch?v=vZ734NWnAHA",
    sinopsis:"La nave en la que viaja la princesa Leia es capturada por las tropas imperiales al mando del temible Darth Vader. Antes de ser atrapada, Leia consigue introducir un mensaje en su robot R2-D2, quien acompañado de su inseparable C-3PO logran escapar. Tras aterrizar en el planeta Tattooine son capturados y vendidos al joven Luke Skywalker, quien descubrirá el mensaje oculto que va destinado a Obi Wan Kenobi, maestro Jedi a quien Luke debe encontrar para salvar a la princesa."},

    {id:5,
    title:"Star Wars Episodio V: El Imperio Contraataca",
    image:"https://res.cloudinary.com/duvugx7r9/image/upload/v1717109957/proyectCinema/lukeyoda_q2xu.1280_s7bp4w.webp",
    director:"Irvin Kershner",
    year:1980,
    trailer:"https://www.youtube.com/watch?v=JNwNXF9Y6kY",
    sinopsis:"Son tiempos adversos para la rebelión. Aunque la Estrella de la Muerte ha sido destruida, las tropas imperiales han hecho salir a las fuerzas rebeldes de sus bases ocultas y los persiguen a través de la galaxia. Tras escapar de la terrible Flota Imperial, un grupo de guerreros de la libertad, encabezados por Luke Skywalker, ha establecido una nueva base secreta en el remonto mundo helado de Hoth."},
    
    {id:6,
    title:"Star Wars Episodio VI: El Regreso del Jedi",
    image:"https://res.cloudinary.com/duvugx7r9/image/upload/v1717109983/proyectCinema/1366_2000_ubw4jc.webp",
    director:"Richard Marquand",
    year:1983,
    trailer:"https://www.youtube.com/watch?v=16YLjTkK5jE",
    sinopsis:"Seis meses después de que Han Solo fuera capturado y congelado en carbonita en la Ciudad de las Nubes, el Imperio Galáctico está construyendo una nueva Estrella de la Muerte. Mientras tanto, el joven Luke lucha para alcanzar la maestría jedi."},
]